services:
  db:
    image: postgres:16
    container_name: Brana-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: Brana
      POSTGRES_PASSWORD: Brana
      POSTGRES_DB: Brana
    ports:
      - "5433:5432"
    volumes:
      - Brana-db-data:/var/lib/postgresql/data
volumes:
  Brana-db-data:
